### ISSUE TITLE
linkda "target=_blank" yozilmagan

### ISSUE THREAD

**Issue by thisisal1yev** [Andarov/moshina-bozor#1]
Telegram sahifangizga olib otuvchi linkda **"target=_blank"** yo'q 
![image](https://github.com/Andarov/avto-expert/assets/142145784/779b1382-9798-4a3d-90e7-8ea6bb9df21d)

**Comment by thisisal1yev** [comment]
Bu muommoni tog'irlash oson "a" tegi ichiga "target" atributini yozamiz va atributning "value"siga  "_blank"deb yozilladi. Muomo hal😎.

**Comment by yaxyobekuz** [comment]
muammo hal qilindi. e'tiboringiz uchun rahmat🔥
